#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main(void)
{
    int i;
    char password[7];

    // Seed the random number generator with the current time
    srand(time(NULL));

    // Generate the password
    for (i = 0; i < 6; i++)
    {
        // The password is generated by using a simple formula (you can adjust the range as needed)
        password[i] = (rand() % 94) + 32; // ASCII range from 32 (space) to 125 (~)
    }

    password[6] = '\0'; // Null-terminate the string

    // Print the generated password
    printf("%s\n", password);

    return 0;
}
